DROP TABLE IF EXISTS `champions`;
CREATE TABLE IF NOT EXISTS `champions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `championName` varchar(255) DEFAULT NULL,
  `badAgainst1` varchar(255) DEFAULT NULL,
  `badAgainst2` varchar(255) DEFAULT NULL,
  `badAgainst3` varchar(255) DEFAULT NULL,
  `badAgainst4` varchar(255) DEFAULT NULL,
  `badAgainst5` varchar(255) DEFAULT NULL,
  `badAgainst6` varchar(255) DEFAULT NULL,
  `goodWith1` varchar(255) DEFAULT NULL,
  `goodWith2` varchar(255) DEFAULT NULL,
  `goodWith3` varchar(255) DEFAULT NULL,
  `goodWith4` varchar(255) DEFAULT NULL,
  `goodWith5` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

INSERT INTO `champions` (`id`, `championName`, `badAgainst1`,`badAgainst2`,`badAgainst3`,`badAgainst4`,`badAgainst5`,`badAgainst6`,`goodWith1`,`goodWith2`,`goodWith3`,`goodWith4`,`goodWith5`) VALUES
(NULL, 'Aatrox', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Ahri', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Akali', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Amumu', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Anivia', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Annie', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Ashe', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Azir', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Bard', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Blitzcrank', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Brand', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Braum', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Caitlyn', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Cassiopeia', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, "Cho'Gath", 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Corki', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Darius', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Diana', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Dr.Mundo', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Draven', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Elise', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Evelynn', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Ezreal', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Fiddlesticks', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Fiora', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Fizz', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Galio', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Gangplank', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Garen', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Gnar', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Gragas', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Graves', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Hecarim', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Heimerdinger', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Irelia', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Janna', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Jarven IV', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Jax', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Jayce', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Jinx', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Kalista', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Karma', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Karthus', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Kassadin', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Katarina', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Kayle', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Kennen', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, "Kha'Zix", 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, "Kog'Maw", 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'LeBlanc', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Lee Sin', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Leona', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Lissandra', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Lucian', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Lulu', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Lux', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Malphite', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Malzahar', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Maokai', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Master Yi', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Miss Fortune', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Mordekaiser', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Morgana', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Nami', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Nasus', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Nautilus', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Nidalee', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Nocturne', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Nunu', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Olaf', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Orianna', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Pantheon', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Poppy', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Quinn', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Rammus', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, "Rek'Sai", 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Renekton', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Rengar', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Riven', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Rumble', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Ryze', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Sejuani', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Shaco', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Shen', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Shyvana', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Singed', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Sion', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Sivir', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Skarner', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Sona', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Soraka', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Swain', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Syndra', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Talon', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Taric', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Teemo', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Thresh', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Tristana', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Trundle', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Tryndamere', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Twisted Fate', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Twitch', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Udyr', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Urgot', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Varus', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Vayne', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Veigar', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, "Vel'Koz", 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Vi', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Viktor', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Vladimir', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Volibear', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Warwick', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Wukong', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Xerath', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Xin Zhao', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Yasuo', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Yorick', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Zac', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Zed', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Ziggs', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Zilean', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Zyra', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr');



