DROP TABLE IF EXISTS `champions`;
CREATE TABLE IF NOT EXISTS `champions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `championName` varchar(255) DEFAULT NULL,
  `badAgainst1` varchar(255) DEFAULT NULL,
  `badAgainst2` varchar(255) DEFAULT NULL,
  `badAgainst3` varchar(255) DEFAULT NULL,
  `badAgainst4` varchar(255) DEFAULT NULL,
  `badAgainst5` varchar(255) DEFAULT NULL,
  `badAgainst6` varchar(255) DEFAULT NULL,
  `goodWith1` varchar(255) DEFAULT NULL,
  `goodWith2` varchar(255) DEFAULT NULL,
  `goodWith3` varchar(255) DEFAULT NULL,
  `goodWith4` varchar(255) DEFAULT NULL,
  `goodWith5` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

INSERT INTO `champions` (`id`, `championName`, `badAgainst1`,`badAgainst2`,`badAgainst3`,`badAgainst4`,`badAgainst5`,`badAgainst6`,`goodWith1`,`goodWith2`,`goodWith3`,`goodWith4`,`goodWith5`) VALUES
(NULL, 'Aatrox', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Ahri', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Akali', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Amumu', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Anivia', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Annie', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Ashe', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Azir', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Bard', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Blitzcrank', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Brand', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Braum', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Caitlyn', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Cassiopeia', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, "Cho'Gath", 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Corki', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Darius', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Diana', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Dr.Mundo', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Draven', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Elise', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Evelynn', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Ezreal', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Fiddlesticks', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Fiora', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Fizz', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Galio', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Gangplank', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Garen', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Gnar', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Gragas', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Graves', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Hecarim', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Heimerdinger', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Irelia', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Janna', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Jarven IV', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Jax', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr'),
(NULL, 'Jayce', 'Annie','Braum','Fiddlesticks','Gangplank','Gargas','Heimerdinger','Nidalee','Xin Zhao','Heimerdinger','Nasus','Udyr');


